{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "argo-apid-helper.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "argo-apid-helper.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "argo-apid-helper.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
